- hosts: web-server
  remote_user: ubuntu
  become: true

  vars_prompt:
    - name: db_hostname
      prompt: Etner db hostname
    - name: db_password
      prompt: Enter db password

  tasks:
    - name: Update all packages
      apt:
        update_cache: yes
        name: "*"
        state: latest

    - name: Install dependencies
      apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - htop

    - name: Install apt key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present
        keyring: /etc/apt/trusted.gpg.d/docker.gpg
      
    - name: Install Docker repo
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
        state: present
        filename: docker

    - name: Install Docker
      apt:
        update_cache: yes
        pkg:
          - docker-ce 
          - docker-ce-cli 
          - containerd.io 
          - docker-compose-plugin
    
    - name: Install pip3
      apt: 
        name: python3-pip 
        state: present 

    - name: Install Docker SDK for Python and docker-compose
      pip:
        name: ["docker", "docker-compose"]

    - name: Install Git repo
      apt_repository:
       repo: 'ppa:git-core/ppa'
       state: present

    - name: Install Git
      apt:
       name: git
       state: present
       update_cache: yes

    - name: Push private deploy key
      copy:
        src: ~/.ssh/flaskapp_key_rsa
        dest: ~/.ssh/flaskapp_key_rsa

    - name: Correct SSH deploy key permissions
      file: 
        dest: ~/.ssh/flaskapp_key_rsa
        mode: 0600

    - name: Clone repository
      git:
        repo: git@github.com:platinum139/FlaskApp.git
        dest: /home/ubuntu/FlaskApp
        version: aws-deploy
        clone: yes
        update: yes
        accept_hostkey: yes
        key_file: ~/.ssh/flaskapp_key_rsa

    - name: Create .env
      copy:
        dest: "/home/ubuntu/FlaskApp/.env"
        content: |
          DB_HOSTNAME={{db_hostname}}
          DB_PASSWORD={{db_password}}

    - name: Docker Compose Up
      docker_compose:
        project_src: /home/ubuntu/FlaskApp
        state: present
        build: yes
